# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3770c5255c2ee9fc3461bb0125ec1626909137b3042f7d962ae1a9ebe82b9dbac886f07cf70f7bd22eca5a0064fd9405631a54ddbca9054d579f1ef545f5e347

test:
  secret_key_base: ee72b89aec77d850b178c71450789e81c6777efb1b82df597bd810aeebd966a49d2c61bfa832c04dce7cd5165bb3b102bb5da64c8433bd50c0e772a2f57fb915

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
